# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --no-cache-dir --upgrade -r requirements.txt
    - name: Execute unit test
      run: |
        python -m unittest discover tests
    - name: Docker login
      env: 
         DOCKER_USER : ${{secrets.DOCKER_USER}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD        
    - name: Build docker
      run: |
        docker build -t devco/fast-api-example:latest . && docker images -a
    - name: Push dockerhub
      run: |
        docker push ${{secrets.DOCKER_USER}}test/devco/fast-api-example:latest
